### ISSUE TITLE
Invalid meta platform CentOS7

### ISSUE THREAD

**Issue by karras** [adfinis-sygroup/ansible-roles#50]
I've just played around with Galaxy and I wasn't able to import a role with the following platform:
```
   platforms:
   - name: CentOS
       versions:
         - 7
```
It said: ` Invalid platform: CentOS-7 (skipping) `

I think the platform for CentOS/RHEL has to be `EL`.
